# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  schedule:
    - cron: '* * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
           python-version: '3.x'

      # Runs a single command using the runners shell
      - name: Run curl
        run: curl http://141.164.46.127:8000

      # Runs a set of commands using the runners shell
      - name: Run test
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install requests
          pip install html2text
          pip install sqlalchemy
          pip install flask_sqlalchemy
          pip install parsel
          pip install pyyaml
          python hello.py
          echo test, and deploy your project.
